{{- if eq .Values.laravel.database.connection "sqlite" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "laravel-octane.fullname" . }}-db-init
  labels:
    {{- include "laravel-octane.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      {{- if .Values.persistence.enabled }}
      initContainers:
      - name: init-db-file
        image: busybox:latest
        command: ['sh', '-c']
        args:
        - |
          mkdir -p /app/database
          if [ ! -f /app/database/database.sqlite ]; then
            touch /app/database/database.sqlite
          fi
          chown -R 1000:1000 /app/database
          chmod -R 775 /app/database
        volumeMounts:
        - name: database
          mountPath: /app/database
      {{- end }}
      containers:
      - name: migrate
        {{- if .Values.build.enabled }}
        image: {{ include "laravel-octane.fullname" . }}:{{ .Values.build.tag | default "latest" }}
        {{- else }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        {{- end }}
        command: ['php', 'artisan', 'migrate', '--force']
        envFrom:
        - configMapRef:
            name: {{ include "laravel-octane.fullname" . }}
        - secretRef:
            name: {{ include "laravel-octane.fullname" . }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: database
          mountPath: /app/database
        {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: {{ include "laravel-octane.fullname" . }}-database
      {{- end }}
{{- end }}